name: Docker Image
on:
  push:
    branches:
      - "master"
      - "try-ci"
    tags:
      - "v*.*.*"
  pull_request:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Env
        id: vars
        shell: bash
        run: |
          echo "SHA_SHORT=$(git rev-parse --short HEAD)" >> "${GITHUB_ENV}"
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true
          driver: docker
          platforms: linux/arm64

      - name: Login to GitHub Packages
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/arm64
          file: ./.docker/Dockerfile-build
          push: true
          tags: ghcr.io/theplant/kratos:${{ env.SHA_SHORT }}
          build-args: |
            COMMIT=${{ env.SHA_SHORT }}
            BUILD_DATE=$(shell date -u +"%Y-%m-%dT%H:%M:%SZ")
